config/routes.rb
Rails.application.routes.draw do
  resources :apps
  devise_for :users
  get 'welcome/index'
  root to:'welcome#index'

  #API Controller

  namespace :api, defaults: { format: :json } do
  #Namespace keeps the API route seperate from the other routes/Expect request in JSON
     #Checks to see if events can be created
     match 'create_event', to: 'events#create', via: [:options]
     resources :events, only: [:create]
     #The app need to support the API for one resource
  end
end

app/models/app.rb
class App < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :app
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :apps

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController
  before_filter :set_access_control_headers

  def set_access_control_headers
    #Allow request from any origin
    headers['Access-Control-Allow-Origin'] = '*'
    # Permit the POST,GET, OPTION request methods
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    # Allow the header Content-Type that declare the data type being sent
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  skip_before_action :verify_authenticity_token
   # necessary in all controllers that will respond with JSON
  respond_to :json

  def create
    registered_application = App.find_or_create_by(url: request.env['HTTP_ORIGIN'])
    @event = registered_application.events.find_by(event_params)
    if @event == nil
      @event = registered_application.events.build(event_params)
      @event.count = 1
      if @event.save
        render json: @event, status: :created
      else
        render json: "Broken event", status: :unprocessable_entity
      end
    else
      @event.count += 1
      if @event.save
        render json: @event, status: :created
      else
        render json: "Broken event", status: :unprocessable_entity
      end
    end
  end

  private
  # Error responses and before_action blocking work differently with Javascript requests.
  # Rather than using before_actions to authenticate actions, we suggest using
  # "guard clauses" like `permission_denied_error unless condition`
    def event_params
       params.require(:event).permit(:name)
    end

  def permission_denied_error
    error(403, 'Permission Denied!')
  end

  def error(status, message = 'Something went wrong')
    response = {
      response_type: "ERROR",
      message: message
  }

  render json: response.to_json, status: status
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def create
    @app = App.new(params.require(:app).permit(:title, :url))
    @app.user_id = 1
    if @app.save
      flash[:notice] = "App was saved!"
      redirect_to @app
    else
      flash[:error] = "There an error, oh noes!Please try again!"
      render :new
    end
  end

  def new
    @app = App.new
  end

  def show
    @app = App.find(params[:id])
    @events = @app.events.group_by(&:name)
    p @events
  end

  def index
    @apps = App.all
  end

  def edit
    @app = App.find(params[:id])
  end

  def update
    @app = App.find(params[:id])
     if @app.update_attributes(params.require(:app).permit(:title, :url))
       flash[:notice] = "Application was updated."
       redirect_to @app
     else
       flash[:error] = "There was an error saving the app. Please try again."
       render :edit
     end
  end

  def destroy
    @app = App.find(params[:id])
    if @app.destroy
      flash[:notice] = "App was removed."
    else
      flash[:error] = "App couldn't be deleted. Try again."
    end

     respond_to do |format|
       format.html
       format.js
     end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apps/create.html.erb
<h1>Apps#create</h1>
<p>Find me in app/views/apps/create.html.erb</p>

app/views/apps/destroy.js.erb
<% if @app.destroyed? %>
   $('#app-'+<%= @app.id %>).fadeOut();
 <% else %>
   $('#app-'+<%= @app.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
 <% end %>

app/views/apps/edit.html.erb
<h1>Edit Post</h1>
 <div class="row">
   <div class="col-md-12">
     <%= form_for @app do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter App title" %>
       </div>
       <div class="form-group">
         <%= f.label :url %>
         <%= f.text_area :url, rows: 8, class: 'form-control', placeholder: "Enter App body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/apps/index.html.erb
<h1>All Apps</h1>
 <% @apps.each do |app| %>
   <div class="media">
     <div class="media-body">
       <h5 id="app-<%=app.id%>">
         <%= link_to app.title, app %>
         <i class="icon-remove-sign"><%= link_to "Delete", app , method: :delete, remote: true %></i>
       </h5>
     </div>
   </div>
 <% end %>
 <%= link_to "New App", method: :post, remote: true %>

app/views/apps/new.html.erb
<h1>New App</h1>

 <div class="row">
   <div class="col-md-12">
     <%= form_for @app do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter App Title" %>
       </div>
       <div class="form-group">
         <%= f.label :url %>
         <%= f.text_field :url, rows: 8, class: 'form-control', placeholder: "Enter Url" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/apps/show.html.erb
<h1><%= @app.title %></h1>
<h5>App URL: <%= @app.url %></h5>
<h5>App User_id: <%= @app.user_id %></h5>
<br>

<h2> Events </h2>
<% @events.each do |event| %>
    <div>
      <%= event[0] %><span class="badge"><%= event[1].first.count %></span>
    </div>
<% end %>

<br>
<%= link_to "Edit", edit_app_path(@app), class: 'btn btn-success' %>

app/views/apps/update.html.erb
<h1>Apps#update</h1>
<p>Find me in app/views/apps/update.html.erb</p>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
 <head>
   <title>Bloccit</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= stylesheet_link_tag    "application", media: "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
 </head>
 <body>
   <div class="container">
   <ul>
     <ul class="nav nav-tabs">
       <li><%= link_to "Bloccit", welcome_index_path %></li>
       <li class="apps"><%= link_to "Apps", apps_path %></li>
       <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.name %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>

     </ul>
     <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
   <%= yield %>
   </div>

 </body>
 </html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Hello, world!</h1>
  <p>...</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>